deepspeed --module humun_econ_transformer.train_sft \
   --max_len 512 \
   --dataset_path datasets/split.parquet\
   --metadata_path datasets/all_fred_metadata.csv \
   --processed_dataset_path datasets/processed_split\
   --input_key history \
   --output_key forecast \
   --apply_chat_template \
   --train_batch_size 128 \
   --micro_train_batch_size 8 \
   --max_samples 500000 \
   --pretrain Qwen/Qwen2.5-7B-Instruct \
   --save_path ./checkpoint/qwen_2_5_7b_instruct \
   --save_steps -1 \
   --logging_steps 1 \
   --eval_steps -1 \
   --zero_stage 3 \
   --max_epochs 1 \
   --packing_samples \
   --bf16 \
   --flash_attn \
   --learning_rate 5e-6 \
   --gradient_checkpointing \